openapi: 3.1.0
info:
    title: Obsrvr API
    version: 0.0.1
servers:
    - url: https://api.withobsrvr.com/{version}
      description: Obsrvr API
      variables:
          version:
              default: v1
paths:
    /horizon/managedInstances:
        get:
            summary: List All Managed Instances
            description: List All Managed Instances
            tags:
                - ManagedInstances
            operationId: get-managed-instances
            security:
                - api_key: []
            responses:
                "200":
                    description: "OK"
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    instances:
                                        type: array
                                        items:
                                            $ref: "#/components/schemas/instance"
                "400":
                    description: Bad Request
                "401":
                    description: Unauthorized
                "403":
                    description: Forbidden
                "404":
                    description: Not Found
        post:
            summary: "Create a Managed Instance"
            tags:
                - ManagedInstances
            operationId: create-managed-instance
            security:
                - api_key: []
            responses:
                "202":
                    description: Created
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    instance:
                                        $ref: "#/components/schemas/instance"
                "400":
                    description: Bad Request
                "401":
                    description: Unauthorized
                "403":
                    description: Forbidden
                "404":
                    description: Not Found
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                region:
                                    type: string
                                    description: The Region ID of where the instance is located
                                size:
                                    type: string
                                    description: The Size ID of the instance
                                name:
                                    type: string
                                    description: The name of the instance
                                tag:
                                    type: string
                                    description: User-supplied tags for the instance
                            required:
                                - region
                                - size
                                - name
    /horizon/managedInstances/{instance-id}:
        parameters:
            - name: instance-id
              in: path
              required: true
              schema:
                  type: string
        get:
            summary: Get Managed Instance
            description: Get Managed Instance
            tags:
                - ManagedInstance
            operationId: get-managed-instance
            security:
                - api_key: []
            responses:
                "200":
                    description: "OK"
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    instances:
                                        $ref: "#/components/schemas/instance"
                "400":
                    description: Bad Request
                "401":
                    description: Unauthorized
                "403":
                    description: Forbidden
                "404":
                    description: Not Found
    /tags:
        get:
            summary: List All Tags
            description: List All Tags
            tags:
                - Tags
            operationId: list-tags
            security:
                - api_key: []
            responses:
                "200":
                    description: "OK"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/status"
                "400":
                    description: Bad Request
                "401":
                    description: Unauthorized
                "403":
                    description: Forbidden
                "404":
                    description: Not Found
        post:
            summary: Create a new Tag
            description: Create a new Tag
            tags:
                - Tags
            operationId: "create-tag"
            security:
                - api_key: []
            responses:
                "201":
                    description: Created
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/status"

                              
components:
    schemas:
        instance:
            title: "instance"
            type: object
            tags: 
                - Instances
            properties:
                id:
                    type: string
                    description: "A unique ID for the instance"
                ipv4:
                    type: string
                    description: "IP Address of the instance"
                date_created:
                    type: string
                    description: "The date this instance was created"
                name:
                    type: string
                    description: "The user-supplied name of the instance"
                region:
                    type: string
                    description: "The region of the instance"
                size:
                    type: string
                    description: "Size of instance"
                status:
                    type: string
                    description: "The current status"
                tag:
                    type: string
                    description: "The user-supplied tag for this instance"
                version:
                    type: string
                    description: "The version of the software for this instance"

        region:
            title: "region"
            type: object
            tags:
                - region
            description: "Region Information"
            properties:
                id:
                    type: string
                    description: "A unique ID for the Region"
                name: 
                    type: string
                    description: "Name for the region"
                features:
                    type: array
                    description: "An array of product features available in this region"
                    items:
                        type: string
                sizes:
                    type: array
                    description: "An array of available sizes in this region"
                    items:
                        type: string
        plans:
            title: plans
            type: object
            tags:
                - plans
            descripton: Plans for instances
            properties:
                id:
                    type: string
                    description: A unique ID for the Plan
                name:
                    type: string
                    description: The Plan name
                vcpu_count:
                    type: string
                    description: The number of vCPUs in this Plan
                ram:
                    type: integer
                    description: The amount of RAM in MB
                disk:
                    type: integer
                    description: The disk size in GB
                bandwidth:
                    type: integer
                    description: The monthly bandwidth quota in GB
                price_monthly:
                    type: integer
                    description: The monthly cost in US Dollars
                price_hourly:
                    type: integer
                    description: The hourly cost in US Dollars
                regions:
                    type: array
                    description: An array of Regions where this plan is valid for use
                    items:
                        type: string
                available:
                    type: boolean
                    description: Availability of this Plan
        status:
            type: string
            maxLength: 256
            description: A Message
            example: "OK"
    securitySchemes:
        api_key:
            type: apiKey
            name: api_key
            in: header